---
title: "calicrop"
author: "Yingfei Jiang"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(ggpubr)

e_45 <- read_csv("CanESM2_45.csv")
e_85 <- read_csv("CanESM2_85.csv")
c_45 <- read_csv("CCSM4_45.csv")
c_85 <- read_csv("CCSM4_85.csv")
h_45 <- read_csv("HadGEM2-CC365_45.csv")
h_85 <- read_csv("HadGEM2-CC365_85.csv")

```

```{r}

e_45 <- e_45 %>% 
  mutate(parsedate = mdy(date)) %>% 
  mutate(month = month(parsedate),
         year = year(parsedate))

e_85 <- e_85 %>% 
  mutate(parsedate = mdy(date)) %>% 
  mutate(month = month(parsedate),
         year = year(parsedate))

c_45 <- c_45 %>% 
  mutate(parsedate = mdy(Date)) %>% 
  mutate(month = month(parsedate),
         year = year(parsedate))

c_85 <- c_85 %>% 
  mutate(parsedate = mdy(Date)) %>% 
  mutate(month = month(parsedate),
         year = case_when(
           year(parsedate) <= 2000 ~ year(parsedate) + 100,
           year(parsedate) > 2000 ~ year(parsedate)
           ))

h_45 <- h_45 %>% 
  mutate(parsedate = mdy(date)) %>% 
  mutate(month = month(parsedate),
         year = year(parsedate))

h_85 <- h_85 %>% 
  mutate(parsedate = mdy(date)) %>% 
  mutate(month = month(parsedate),
         year = year(parsedate))

```


```{r}

#Create a dataframe

crop <- data.frame("year" = 2007:2099)



```

```{r}

#table grape

g_c_45 <- rep(0, 93)
g_c_85 <- rep(0, 93)
g_e_45 <- rep(0, 93)
g_e_85 <- rep(0, 93)
g_h_45 <- rep(0, 93)
g_h_85 <- rep(0, 93)

for (x in crop$year) {
  tn7_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 7) %>% select(min_temp)) - 273.15
  tn7_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 7) %>% select(min_temp)) - 273.15
  tn7_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 7) %>% select(min_temp)) - 273.15
  tn7_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 7) %>% select(min_temp)) - 273.15
  tn7_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 7) %>% select(min_temp)) - 273.15
  tn7_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 7) %>% select(min_temp)) - 273.15
  tn4_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  p10_c_45 = as.numeric(c_45 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_c_85 = as.numeric(c_85 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_e_45 = as.numeric(e_45 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_e_85 = as.numeric(e_85 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_h_45 = as.numeric(h_45 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_h_85 = as.numeric(h_85 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p1_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 1) %>% select(precip))
  

  
  g_c_45[x-2006] = 6.93 * tn7_c_45 - 0.19 * tn7_c_45^2 + 2.61 * tn4_c_45 - 0.15 * tn4_c_45^2 + 0.035 * p1_c_45 + 0.024 * p1_c_45^2 + 1.71 * p10_c_45 - 0.673 * p10_c_45^2 - 73.89
  g_c_85[x-2006] = 6.93 * tn7_c_85 - 0.19 * tn7_c_85^2 + 2.61 * tn4_c_85 - 0.15 * tn4_c_85^2 + 0.035 * p1_c_85 + 0.024 * p1_c_85^2 + 1.71 * p10_c_85 - 0.673 * p10_c_85^2 - 73.89
  g_e_45[x-2006] = 6.93 * tn7_e_45 - 0.19 * tn7_e_45^2 + 2.61 * tn4_e_45 - 0.15 * tn4_e_45^2 + 0.035 * p1_e_45 + 0.024 * p1_e_45^2 + 1.71 * p10_e_45 - 0.673 * p10_e_45^2 - 73.89
  g_e_85[x-2006] = 6.93 * tn7_e_85 - 0.19 * tn7_e_85^2 + 2.61 * tn4_e_85 - 0.15 * tn4_e_85^2 + 0.035 * p1_e_85 + 0.024 * p1_e_85^2 + 1.71 * p10_e_85 - 0.673 * p10_e_85^2 - 73.89
  g_h_45[x-2006] = 6.93 * tn7_h_45 - 0.19 * tn7_h_45^2 + 2.61 * tn4_h_45 - 0.15 * tn4_h_45^2 + 0.035 * p1_h_45 + 0.024 * p1_h_45^2 + 1.71 * p10_h_45 - 0.673 * p10_h_45^2 - 73.89
  g_h_85[x-2006] = 6.93 * tn7_h_85 - 0.19 * tn7_h_85^2 + 2.61 * tn4_h_85 - 0.15 * tn4_h_85^2 + 0.035 * p1_h_85 + 0.024 * p1_h_85^2 + 1.71 * p10_h_85 - 0.673 * p10_h_85^2 - 73.89
  
}

```

```{r}

table_grape <- data.frame("year" = crop$year, "c_45" = g_c_45, "c_85" = g_c_85, "e_45" = g_e_45, "e_85" = g_e_85, "h_45" = g_h_45, "h_85" = g_h_85)

table_grape_plot <- ggplot(table_grape) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  geom_line(aes(x = year, y = e_45, color = "CanESM2 (rcp4.5)")) +
  geom_line(aes(x = year, y = e_85, color = "CanESM2 (rcp8.5)")) +
  geom_line(aes(x = year, y = h_45, color = "HadGEM2-CC365 (rcp4.5)")) +
  geom_line(aes(x = year, y = h_85, color = "HadGEM2-CC365 (rcp8.5)"))+
  scale_colour_manual("Model", values= c("skyblue", "sienna1", "turquoise3", "violetred", "springgreen3", "magenta")) +
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Table Grape Yield Anomaly Projection")+
  scale_x_continuous(breaks = seq(2000, 3000, by = 20))
  
table_grape_plot

```


```{r}

#almond

a_c_45 <- rep(0, 93)
a_c_85 <- rep(0, 93)
a_e_45 <- rep(0, 93)
a_e_85 <- rep(0, 93)
a_h_45 <- rep(0, 93)
a_h_85 <- rep(0, 93)

for (x in crop$year) {

  tn2_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 2) %>% select(min_temp)) - 273.15
  tn2_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 2) %>% select(min_temp)) - 273.15
  tn2_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 2) %>% select(min_temp)) - 273.15
  tn2_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 2) %>% select(min_temp)) - 273.15
  tn2_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 2) %>% select(min_temp)) - 273.15
  tn2_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 2) %>% select(min_temp)) - 273.15

  p1_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 1) %>% select(precip))
  p1_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 1) %>% select(precip))
  

  
  a_c_45[x-2006] = -0.015 * tn2_c_45 - 0.0046 * tn2_c_45^2 - 0.07 * p1_c_45 + 0.0043 * p1_c_45^2 + 0.28
  a_c_85[x-2006] = -0.015 * tn2_c_85 - 0.0046 * tn2_c_85^2 - 0.07 * p1_c_85 + 0.0043 * p1_c_85^2 + 0.28
  a_e_45[x-2006] = -0.015 * tn2_e_45 - 0.0046 * tn2_e_45^2 - 0.07 * p1_e_45 + 0.0043 * p1_e_45^2 + 0.28
  a_e_85[x-2006] = -0.015 * tn2_e_85 - 0.0046 * tn2_e_85^2 - 0.07 * p1_e_85 + 0.0043 * p1_e_85^2 + 0.28
  a_h_45[x-2006] = -0.015 * tn2_h_45 - 0.0046 * tn2_h_45^2 - 0.07 * p1_h_45 + 0.0043 * p1_h_45^2 + 0.28
  a_h_85[x-2006] = -0.015 * tn2_h_85 - 0.0046 * tn2_h_85^2 - 0.07 * p1_h_85 + 0.0043 * p1_h_85^2 + 0.28
  
}

```

```{r}

almond <- data.frame("year" = crop$year, "c_45" = a_c_45, "c_85" = a_c_85, "e_45" = a_e_45, "e_85" = a_e_85, "h_45" = a_h_45, "h_85" = a_h_85)

almond_plot <- ggplot(almond) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  geom_line(aes(x = year, y = e_45, color = "CanESM2 (rcp4.5)")) +
  geom_line(aes(x = year, y = e_85, color = "CanESM2 (rcp8.5)")) +
  geom_line(aes(x = year, y = h_45, color = "HadGEM2-CC365 (rcp4.5)")) +
  geom_line(aes(x = year, y = h_85, color = "HadGEM2-CC365 (rcp8.5)"))+
  scale_colour_manual("Model", values= c("skyblue", "sienna1", "turquoise3", "violetred", "springgreen3", "magenta")) +
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Almond Yield Anomaly Projection")+
  scale_x_continuous(breaks = seq(2000, 3000, by = 20))
  
almond_plot

```

```{r}

#wine grape

w_c_45 <- rep(0, 93)
w_c_85 <- rep(0, 93)
w_e_45 <- rep(0, 93)
w_e_85 <- rep(0, 93)
w_h_45 <- rep(0, 93)
w_h_85 <- rep(0, 93)

for (x in crop$year) {

  tn4_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15
  tn4_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 4) %>% select(min_temp)) - 273.15

  p6_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 6) %>% select(precip))
  p6_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 6) %>% select(precip))
  p6_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 6) %>% select(precip))
  p6_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 6) %>% select(precip))
  p6_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 6) %>% select(precip))
  p6_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 6) %>% select(precip))
  
  p9_c_45 = as.numeric(c_45 %>% filter(year == (x-1), month == 9) %>% select(precip))
  p9_c_85 = as.numeric(c_85 %>% filter(year == (x-1), month == 9) %>% select(precip))
  p9_e_45 = as.numeric(e_45 %>% filter(year == (x-1), month == 9) %>% select(precip))
  p9_e_85 = as.numeric(e_85 %>% filter(year == (x-1), month == 9) %>% select(precip))
  p9_h_45 = as.numeric(h_45 %>% filter(year == (x-1), month == 9) %>% select(precip))
  p9_h_85 = as.numeric(h_85 %>% filter(year == (x-1), month == 9) %>% select(precip))
  

  
  w_c_45[x-2006] = 2.65 * tn4_c_45 - 0.17 * tn4_c_45^2 + 4.78 * p6_c_45 - 4.93 * p6_c_45^2 - 2.24 * p9_c_45 + 1.54 * p9_c_45^2 - 10.5
  w_c_85[x-2006] = 2.65 * tn4_c_85 - 0.17 * tn4_c_85^2 + 4.78 * p6_c_85 - 4.93 * p6_c_85^2 - 2.24 * p9_c_85 + 1.54 * p9_c_85^2 - 10.5
  w_e_45[x-2006] = 2.65 * tn4_e_45 - 0.17 * tn4_e_45^2 + 4.78 * p6_e_45 - 4.93 * p6_e_45^2 - 2.24 * p9_e_45 + 1.54 * p9_e_45^2 - 10.5
  w_e_85[x-2006] = 2.65 * tn4_e_85 - 0.17 * tn4_e_85^2 + 4.78 * p6_e_85 - 4.93 * p6_e_85^2 - 2.24 * p9_e_85 + 1.54 * p9_e_85^2 - 10.5
  w_h_45[x-2006] = 2.65 * tn4_h_45 - 0.17 * tn4_h_45^2 + 4.78 * p6_h_45 - 4.93 * p6_h_45^2 - 2.24 * p9_h_45 + 1.54 * p9_h_45^2 - 10.5
  w_h_85[x-2006] = 2.65 * tn4_h_85 - 0.17 * tn4_h_85^2 + 4.78 * p6_h_85 - 4.93 * p6_h_85^2 - 2.24 * p9_h_85 + 1.54 * p9_h_85^2 - 10.5
  
}

```

```{r}

wgrape <- data.frame("year" = crop$year, "c_45" = w_c_45, "c_85" = w_c_85, "e_45" = w_e_45, "e_85" = w_e_85, "h_45" = w_h_45, "h_85" = w_h_85)

wgrape_plot <- ggplot(wgrape) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  geom_line(aes(x = year, y = e_45, color = "CanESM2 (rcp4.5)")) +
  geom_line(aes(x = year, y = e_85, color = "CanESM2 (rcp8.5)")) +
  geom_line(aes(x = year, y = h_45, color = "HadGEM2-CC365 (rcp4.5)")) +
  geom_line(aes(x = year, y = h_85, color = "HadGEM2-CC365 (rcp8.5)"))+
  scale_colour_manual("Model", values= c("skyblue", "sienna1", "turquoise3", "violetred", "springgreen3", "magenta")) +
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Wine Grape Yield Anomaly Projection")+
  scale_x_continuous(breaks = seq(2000, 3000, by = 20))
  
wgrape_plot

```

```{r}

#orange

o_c_45 <- rep(0, 93)
o_c_85 <- rep(0, 93)
o_e_45 <- rep(0, 93)
o_e_85 <- rep(0, 93)
o_h_45 <- rep(0, 93)
o_h_85 <- rep(0, 93)

for (x in crop$year) {

  tn12_c_45 = as.numeric(c_45 %>% filter(year == (x-1), month == 12) %>% select(min_temp)) - 273.15
  tn12_c_85 = as.numeric(c_85 %>% filter(year == (x-1), month == 12) %>% select(min_temp)) - 273.15
  tn12_e_45 = as.numeric(e_45 %>% filter(year == (x-1), month == 12) %>% select(min_temp)) - 273.15
  tn12_e_85 = as.numeric(e_85 %>% filter(year == (x-1), month == 12) %>% select(min_temp)) - 273.15
  tn12_h_45 = as.numeric(h_45 %>% filter(year == (x-1), month == 12) %>% select(min_temp)) - 273.15
  tn12_h_85 = as.numeric(h_85 %>% filter(year == (x-1), month == 12) %>% select(min_temp)) - 273.15

  p5_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 5) %>% select(precip))
  p5_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 5) %>% select(precip))
  p5_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 5) %>% select(precip))
  p5_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 5) %>% select(precip))
  p5_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 5) %>% select(precip))
  p5_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 5) %>% select(precip))
  

  
  o_c_45[x-2006] = 1.08 * tn12_c_45 - 0.2 * tn12_c_45^2 + 4.99 * p5_c_45 - 1.97 * p5_c_45^2 - 2.47
  o_c_85[x-2006] = 1.08 * tn12_c_85 - 0.2 * tn12_c_85^2 + 4.99 * p5_c_85 - 1.97 * p5_c_45^2 - 2.47
  o_e_45[x-2006] = 1.08 * tn12_e_45 - 0.2 * tn12_e_45^2 + 4.99 * p5_e_45 - 1.97 * p5_c_45^2 - 2.47
  o_e_85[x-2006] = 1.08 * tn12_e_85 - 0.2 * tn12_e_85^2 + 4.99 * p5_e_85 - 1.97 * p5_c_45^2 - 2.47
  o_h_45[x-2006] = 1.08 * tn12_h_45 - 0.2 * tn12_h_45^2 + 4.99 * p5_h_45 - 1.97 * p5_c_45^2 - 2.47
  o_h_85[x-2006] = 1.08 * tn12_h_85 - 0.2 * tn12_h_85^2 + 4.99 * p5_h_85 - 1.97 * p5_c_45^2 - 2.47
  
}

```

```{r}

orange <- data.frame("year" = crop$year, "c_45" = o_c_45, "c_85" = o_c_85, "e_45" = o_e_45, "e_85" = o_e_85, "h_45" = o_h_45, "h_85" = o_h_85)

orange_plot <- ggplot(orange) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  geom_line(aes(x = year, y = e_45, color = "CanESM2 (rcp4.5)")) +
  geom_line(aes(x = year, y = e_85, color = "CanESM2 (rcp8.5)")) +
  geom_line(aes(x = year, y = h_45, color = "HadGEM2-CC365 (rcp4.5)")) +
  geom_line(aes(x = year, y = h_85, color = "HadGEM2-CC365 (rcp8.5)"))+
  scale_colour_manual("Model", values= c("skyblue", "sienna1", "turquoise3", "violetred", "springgreen3", "magenta")) +
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Orange Yield Anomaly Projection")+
  scale_x_continuous(breaks = seq(2000, 3000, by = 20))
  
orange_plot

```

```{r}

#walnuts

l_c_45 <- rep(0, 93)
l_c_85 <- rep(0, 93)
l_e_45 <- rep(0, 93)
l_e_85 <- rep(0, 93)
l_h_45 <- rep(0, 93)
l_h_85 <- rep(0, 93)

for (x in crop$year) {

  tx11_c_45 = as.numeric(c_45 %>% filter(year == (x-1), month == 11) %>% select(max_temp)) - 273.15
  tx11_c_85 = as.numeric(c_85 %>% filter(year == (x-1), month == 11) %>% select(max_temp)) - 273.15
  tx11_e_45 = as.numeric(e_45 %>% filter(year == (x-1), month == 11) %>% select(max_temp)) - 273.15
  tx11_e_85 = as.numeric(e_85 %>% filter(year == (x-1), month == 11) %>% select(max_temp)) - 273.15
  tx11_h_45 = as.numeric(h_45 %>% filter(year == (x-1), month == 11) %>% select(max_temp)) - 273.15
  tx11_h_85 = as.numeric(h_85 %>% filter(year == (x-1), month == 11) %>% select(max_temp)) - 273.15

  p2_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 2) %>% select(precip))
  p2_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 2) %>% select(precip))
  p2_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 2) %>% select(precip))
  p2_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 2) %>% select(precip))
  p2_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 2) %>% select(precip))
  p2_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 2) %>% select(precip))
  

  
  l_c_45[x-2006] = 0.68 * tx11_c_45 - 0.02 * tx11_c_45^2 + 0.038 * p2_c_45 - 0.0051 * p2_c_45^2 - 5.83
  l_c_85[x-2006] = 0.68 * tx11_c_85 - 0.02 * tx11_c_85^2 + 0.038 * p2_c_85 - 0.0051 * p2_c_85^2 - 5.83
  l_e_45[x-2006] = 0.68 * tx11_e_45 - 0.02 * tx11_e_45^2 + 0.038 * p2_e_45 - 0.0051 * p2_e_45^2 - 5.83
  l_e_85[x-2006] = 0.68 * tx11_e_85 - 0.02 * tx11_e_85^2 + 0.038 * p2_e_85 - 0.0051 * p2_e_85^2 - 5.83
  l_h_45[x-2006] = 0.68 * tx11_h_45 - 0.02 * tx11_h_45^2 + 0.038 * p2_h_45 - 0.0051 * p2_h_45^2 - 5.83
  l_h_85[x-2006] = 0.68 * tx11_h_85 - 0.02 * tx11_h_85^2 + 0.038 * p2_h_85 - 0.0051 * p2_h_85^2 - 5.83
  
  
}

```

```{r}

walnuts <- data.frame("year" = crop$year, "c_45" = l_c_45, "c_85" = l_c_85, "e_45" = l_e_45, "e_85" = l_e_85, "h_45" = l_h_45, "h_85" = l_h_85)

walnuts_plot <- ggplot(walnuts) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  geom_line(aes(x = year, y = e_45, color = "CanESM2 (rcp4.5)")) +
  geom_line(aes(x = year, y = e_85, color = "CanESM2 (rcp8.5)")) +
  geom_line(aes(x = year, y = h_45, color = "HadGEM2-CC365 (rcp4.5)")) +
  geom_line(aes(x = year, y = h_85, color = "HadGEM2-CC365 (rcp8.5)"))+
  scale_colour_manual("Model", values= c("skyblue", "sienna1", "turquoise3", "violetred", "springgreen3", "magenta")) +
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Walnut Yield Anomaly Projection")+
  scale_x_continuous(breaks = seq(2000, 3000, by = 20))
  
walnuts_plot

```

```{r}

#avocado

d_c_45 <- rep(0, 93)
d_c_85 <- rep(0, 93)
d_e_45 <- rep(0, 93)
d_e_85 <- rep(0, 93)
d_h_45 <- rep(0, 93)
d_h_85 <- rep(0, 93)

for (x in crop$year) {

  tx8_c_45 = as.numeric(c_45 %>% filter(year == (x-1), month == 8) %>% select(max_temp)) - 273.15
  tx8_c_85 = as.numeric(c_85 %>% filter(year == (x-1), month == 8) %>% select(max_temp)) - 273.15
  tx8_e_45 = as.numeric(e_45 %>% filter(year == (x-1), month == 8) %>% select(max_temp)) - 273.15
  tx8_e_85 = as.numeric(e_85 %>% filter(year == (x-1), month == 8) %>% select(max_temp)) - 273.15
  tx8_h_45 = as.numeric(h_45 %>% filter(year == (x-1), month == 8) %>% select(max_temp)) - 273.15
  tx8_h_85 = as.numeric(h_85 %>% filter(year == (x-1), month == 8) %>% select(max_temp)) - 273.15
  
  tn5_c_45 = as.numeric(c_45 %>% filter(year == (x), month == 5) %>% select(min_temp)) - 273.15
  tn5_c_85 = as.numeric(c_85 %>% filter(year == (x), month == 5) %>% select(min_temp)) - 273.15
  tn5_e_45 = as.numeric(e_45 %>% filter(year == (x), month == 5) %>% select(min_temp)) - 273.15
  tn5_e_85 = as.numeric(e_85 %>% filter(year == (x), month == 5) %>% select(min_temp)) - 273.15
  tn5_h_45 = as.numeric(h_45 %>% filter(year == (x), month == 5) %>% select(min_temp)) - 273.15
  tn5_h_85 = as.numeric(h_85 %>% filter(year == (x), month == 5) %>% select(min_temp)) - 273.15

  p10_c_45 = as.numeric(c_45 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_c_85 = as.numeric(c_85 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_e_45 = as.numeric(e_45 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_e_85 = as.numeric(e_85 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_h_45 = as.numeric(h_45 %>% filter(year == (x-1), month == 10) %>% select(precip))
  p10_h_85 = as.numeric(h_85 %>% filter(year == (x-1), month == 10) %>% select(precip))
  

  
  d_c_45[x-2006] = 17.71 * tx8_c_45 - 0.29 * tx8_c_45^2 + 3.25 * tn5_c_45 - 0.14 * tn5_c_45^2 + p10_c_45 - 0.31 * p10_c_45^2 - 288.09
  d_c_85[x-2006] = 17.71 * tx8_c_85 - 0.29 * tx8_c_85^2 + 3.25 * tn5_c_85 - 0.14 * tn5_c_85^2 + p10_c_85 - 0.31 * p10_c_85^2 - 288.09
  d_e_45[x-2006] = 17.71 * tx8_e_45 - 0.29 * tx8_e_45^2 + 3.25 * tn5_e_45 - 0.14 * tn5_e_45^2 + p10_e_45 - 0.31 * p10_e_45^2 - 288.09
  d_e_85[x-2006] = 17.71 * tx8_e_85 - 0.29 * tx8_e_85^2 + 3.25 * tn5_e_85 - 0.14 * tn5_e_85^2 + p10_e_85 - 0.31 * p10_e_85^2 - 288.09
  d_h_45[x-2006] = 17.71 * tx8_h_45 - 0.29 * tx8_h_45^2 + 3.25 * tn5_h_45 - 0.14 * tn5_h_45^2 + p10_h_45 - 0.31 * p10_h_45^2 - 288.09
  d_h_85[x-2006] = 17.71 * tx8_h_85 - 0.29 * tx8_h_85^2 + 3.25 * tn5_h_85 - 0.14 * tn5_h_85^2 + p10_h_85 - 0.31 * p10_h_85^2 - 288.09
  
  
  
}

```

```{r}

avocado <- data.frame("year" = crop$year, "c_45" = d_c_45, "c_85" = d_c_85, "e_45" = d_e_45, "e_85" = d_e_85, "h_45" = d_h_45, "h_85" = d_h_85)

avocado_plot <- ggplot(avocado) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  geom_line(aes(x = year, y = e_45, color = "CanESM2 (rcp4.5)")) +
  geom_line(aes(x = year, y = e_85, color = "CanESM2 (rcp8.5)")) +
  geom_line(aes(x = year, y = h_45, color = "HadGEM2-CC365 (rcp4.5)")) +
  geom_line(aes(x = year, y = h_85, color = "HadGEM2-CC365 (rcp8.5)"))+
  scale_colour_manual("Model", values= c("skyblue", "sienna1", "turquoise3", "violetred", "springgreen3", "magenta")) +
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Avocado Yield Anomaly Projection")+
  scale_x_continuous(breaks = seq(2000, 3000, by = 20))
  
avocado_plot

```

```{r}

almond <- almond %>% 
  mutate(crop = "almond")

avocado <- avocado %>% 
  mutate(crop = "avocado")

orange <- orange %>% 
  mutate(crop = "orange")

walnuts <- walnuts %>% 
  mutate(crop = "walnut")

tgrape <- table_grape %>% 
  mutate(crop = "table grape")

wgrape <- wgrape %>% 
  mutate(crop = "wine grape")

```

```{r}
grand_df <- rbind(almond, avocado, orange, walnuts, tgrape, wgrape)

grand_df <- grand_df %>% 
  group_by(crop)

memo_plot <- ggplot(grand_df) +
  geom_line(aes(x = year, y = c_45, color = "CCSM4 (rcp4.5)")) +
  geom_line(aes(x = year, y = c_85, color = "CCSM4 (rcp8.5)")) +
  facet_wrap(~crop, scale = "free")+
  theme_pubr()+
  labs(x = "Year", y = "Yield Anomaly (tonne/acre)", title = "Yield Anomaly Projection")+
  scale_colour_manual("Model", values= c("blue", "red"))+
  theme(axis.text.x=element_text(size=rel(0.75)), axis.text.y=element_text(size=rel(0.75)))

memo_plot
```

